### ISSUE TITLE
Arbitrary data field

### ISSUE THREAD

**Issue by oleyka** [kalefranz/auxlib#1]
Hi Kale,

it would be nice to have a way to define arbitrary data fields using auxlib. One use case for this is here: https://www.opsgenie.com/docs/web-api/alert-api#createAlertRequest 

The "details" field is defined as this:
- Set of user defined properties. This will be specified as a nested JSON map such as: `"details" : {"prop1":"prop1Value", "prop2":"prop2Value"}`

**Comment by oleyka** [comment]
Another use case with the same api: a list of arbitrarily named groups (https://www.opsgenie.com/docs/web-api/alert-api#listRecipients).

**Comment by kalefranz** [comment]
Added a while ago with `MapField` https://github.com/kalefranz/auxlib/blob/develop/auxlib/entity.py#L342
